//API endpoints REST
const prefix = '/api/Query/anyProcedure/';
export default Object.freeze({
    student: prefix + 'delete_students',
    group: prefix + 'delete_groups',
    direction: prefix + 'delete_directions',
    profile: prefix + 'delete_profiles',
    courseWork: prefix + 'delete_course_work',
    role: prefix + 'ums.delete_roles',
    deleteProcedureUser: prefix + 'ums.delete_procedure_user',
    deleteFunctionUser: prefix + 'ums.delete_function_user',
    deleteUserRoleByUserId: prefix + 'ums.delete_user_role_by_user_id',
    deleteUser: prefix + 'ums.delete_users',
    deleteTriggerUser: prefix + 'ums.delete_trigger_user',
    insertUserRole: prefix + 'ums.insert_user_role',
    postGlobalPermission: prefix + 'ums.insert_globalpermissions',
    putGlobalPermission: prefix + 'ums.update_globalpermissions',
    deleteTableFromSql: prefix + 'ums.delete_table_user',
    postPermission: prefix + 'ums.insert_permissions',
    deletePermissions: prefix + 'ums.delete_permissions',
    updateRole:prefix + 'ums.update_roles',
    listener: prefix + 'delete_listeners',
    l_wish_day: prefix + 'delete_l_wish_days',
    l_group_wish_day: prefix + 'delete_l_group_wish_days',
    contract: prefix + 'delete_contracts',
    l_group: prefix + 'delete_l_groups',
    listeners_group_delete: prefix + 'delete_listeners_groups',
    payer: prefix + "delete_payers",
    pay_graph: prefix + 'delete_pay_graph',
    program: prefix + 'delete_programs',
    uploaded_file: prefix + 'delete_uploaded_files',

    deauth_user: prefix + 'update_user_auth_tokens',

    dropSchema: prefix + 'ums.drop_schema',
    postSchema: prefix + 'ums.create_schema',
});
